#! /bin/bash

touch serverhome/server.bin
rm serverhome/server.bin
gcc -o serverhome/server.bin server.c
sudo chown root:root serverhome/server.bin
sudo chmod u+s serverhome/server.bin

touch clienthome/client.bin
rm clienthome/client.bin
gcc -o clienthome/client.bin client.c
